### ISSUE TITLE
🤖 GitHub Actionsワークフローの設定

### ISSUE THREAD

**Issue by suguruTakahashi-1234** [suguruTakahashi-1234/hono-learning#4]
## 概要
CI/CDパイプラインが未設定のため、品質チェックが手動依存となっている。

## 必要なワークフロー
- [ ] **PR時の品質チェック**
  - TypeScript型チェック
  - Biomeリント・フォーマット
  - 単体テスト実行
  - E2Eテスト実行（条件付き）

- [ ] **依存関係のチェック**
  - セキュリティ脆弱性スキャン
  - ライセンスチェック

- [ ] **自動デプロイ**
  - Swagger UIのGitHub Pages公開
  - ビルド成果物の管理

## 推奨設定
```yaml
# .github/workflows/ci.yml
name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm check
```

## 効果
- 品質の自動担保
- レビュー効率の向上
- 本番デプロイの安全性向上

## 優先度
🔥 **緊急度：高** - 開発効率とコード品質に直結
